### ISSUE TITLE
Add requirements.txt for easier repo bootstrapping

### ISSUE THREAD

**Issue by theletterjeff** [Btibert3/pypeds#22]
To ease the process of getting the development environment set up for `pypeds`, add a `requirements.txt` files that includes all third-party dependencies.

For info on creating/using `requirements.txt` files, see [here](https://datagy.io/python-requirements-txt/). Note: `requirements.txt` is best paired with a virtual environment, e.g., one created using Python's `venv` module.

**Comment by Btibert3** [comment]
The dev environment I use is conda and is shown in `environment.yml`, which I know can be a hot topic for some.  This can likely be resolved via a simple export of the environment to `requirements.txt`. There has been some activity on the library used for export to Tableau hyperfiles, so that may need a resolution if packages get upgraded.

**Comment by theletterjeff** [comment]
There seem to be more dependencies in `environment.yml` than in the `pyproject.toml` file. Are there extra packages in `environment.yml` that don't pertain to `pypeds`?

I just built a `requirements.txt` file based on `pyproject.toml` (include the Tableau API dependencies). I'm going to try a clean clone on my Windows machine from my fork and install from there. Assuming it works, I'll open a pull request.
